import { router } from 'expo-router';
import { ArrowLeft, Building2, HeartHandshake, Laptop, Users } from 'lucide-react-native';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Card, ErrorNotice, Field, Screen } from '@/components/ui';
import { request } from '@/lib/api';
import { colors, spacing, typography } from '@/theme';

const choices = [{ label: 'Sponsor tutoring', icon: Users }, { label: 'Support access', icon: Laptop }, { label: 'Community partner', icon: Building2 }];
export default function DonateScreen() {
  const [form, setForm] = useState({ name: '', email: '', organization: '', sponsorType: choices[0].label, message: '' }); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async () => { setLoading(true); setError(''); try { const result = await request<{ message: string }>('/community/sponsor-inquiries', { method: 'POST', authenticated: false, body: JSON.stringify(form) }); setNotice(result.message); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to send inquiry'); } finally { setLoading(false); } };
  return <Screen><Pressable onPress={() => router.back()} style={styles.back}><ArrowLeft size={22} color={colors.ink} /></Pressable><View style={styles.heroIcon}><HeartHandshake size={30} color={colors.coral} /></View><Text style={styles.title}>Help make the right tutor reachable.</Text><Text style={styles.copy}>Cost should not decide whether a student gets help. Tell us how you or your organization would like to support student access.</Text><View style={styles.choices}>{choices.map(({ label, icon: Icon }) => <Pressable key={label} style={[styles.choice, form.sponsorType === label && styles.choiceActive]} onPress={() => set('sponsorType', label)}><Icon size={20} color={form.sponsorType === label ? colors.brand : colors.muted} /><Text style={[styles.choiceText, form.sponsorType === label && styles.choiceTextActive]}>{label}</Text></Pressable>)}</View><Card tone="gold"><Text style={styles.noteTitle}>A conversation, not a payment</Text><Text style={styles.note}>NextDoorLearn is currently collecting sponsorship interest while secure donation processing and partnerships are established.</Text></Card>{error ? <ErrorNotice message={error} /> : null}{notice ? <Card tone="brand"><Text style={styles.notice}>{notice}</Text></Card> : null}<Field label="Name" value={form.name} onChangeText={(v) => set('name', v)} /><Field label="Email" value={form.email} onChangeText={(v) => set('email', v)} keyboardType="email-address" autoCapitalize="none" /><Field label="Organization (optional)" value={form.organization} onChangeText={(v) => set('organization', v)} /><Field label="How would you like to help?" value={form.message} onChangeText={(v) => set('message', v)} multiline /><Button label="Send sponsorship interest" onPress={submit} loading={loading} disabled={!form.name || !form.email} /></Screen>;
}
const styles = StyleSheet.create({ back: { height: 44, justifyContent: 'center' }, heroIcon: { width: 62, height: 62, borderRadius: 31, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.coralSoft }, title: { color: colors.ink, fontFamily: typography.bold, fontSize: 32, lineHeight: 38 }, copy: { color: colors.muted, fontFamily: typography.regular, fontSize: 16, lineHeight: 24 }, choices: { gap: spacing.sm }, choice: { minHeight: 54, borderWidth: 1, borderColor: colors.line, borderRadius: 8, backgroundColor: colors.surface, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.lg }, choiceActive: { borderColor: colors.brand, backgroundColor: colors.brandSoft }, choiceText: { color: colors.muted, fontFamily: typography.medium }, choiceTextActive: { color: colors.brandStrong, fontFamily: typography.bold }, noteTitle: { color: colors.gold, fontFamily: typography.bold, fontSize: 15 }, note: { color: colors.muted, lineHeight: 21 }, notice: { color: colors.brandStrong, fontFamily: typography.medium, lineHeight: 21 } });
