import { router } from 'expo-router';
import { ArrowLeft, Clock3, Plus, Trash2 } from 'lucide-react-native';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Card, ErrorNotice, Field, LoadingState, Screen } from '@/components/ui';
import { request } from '@/lib/api';
import { useData } from '@/lib/hooks';
import { colors, spacing, typography } from '@/theme';

const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
type Slot = { dayOfWeek: number; startTime: string; endTime: string };
export default function AvailabilityScreen() {
  const state = useData<any>(() => request('/availability/me'), []); const [slots, setSlots] = useState<Slot[]>([]); const [timezone, setTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone); const [draft, setDraft] = useState({ dayOfWeek: 1, startTime: '16:00', endTime: '18:00' }); const [initialized, setInitialized] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  // Hydrate editable draft state once after the server response arrives.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (state.data && !initialized) { setSlots(state.data.slots || []); setTimezone(state.data.timezone || timezone); setInitialized(true); } }, [initialized, state.data, timezone]);
  if (state.loading) return <LoadingState />;
  const save = async () => { setSaving(true); setError(''); try { await request('/availability/me', { method: 'PUT', body: JSON.stringify({ slots, timezone }) }); setNotice('Availability published.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save availability'); } finally { setSaving(false); } };
  return <Screen><Pressable onPress={() => router.back()} style={s.back}><ArrowLeft size={22} color={colors.ink} /></Pressable><Text style={s.title}>Weekly availability</Text><Text style={s.copy}>Add recurring windows when students can request tutoring. Times are shown in your saved timezone.</Text>{error || state.error ? <ErrorNotice message={error || state.error} /> : null}{notice ? <Card tone="brand"><Text style={s.notice}>{notice}</Text></Card> : null}<Field label="Timezone" value={timezone} onChangeText={setTimezone} />{slots.map((slot, index) => <Card key={`${slot.dayOfWeek}-${slot.startTime}-${index}`} style={s.slot}><View style={s.clock}><Clock3 size={20} color={colors.brand} /></View><View style={s.slotCopy}><Text style={s.day}>{days[slot.dayOfWeek]}</Text><Text style={s.time}>{slot.startTime} – {slot.endTime}</Text></View><Pressable onPress={() => setSlots((current) => current.filter((_, i) => i !== index))} style={s.delete}><Trash2 size={19} color={colors.red} /></Pressable></Card>)}<Card tone="brand"><Text style={s.section}>Add a weekly window</Text><Text style={s.label}>Day</Text><View style={s.days}>{days.map((day, index) => <Pressable key={day} onPress={() => setDraft((d) => ({ ...d, dayOfWeek: index }))} style={[s.dayButton, draft.dayOfWeek === index && s.dayActive]}><Text style={[s.dayButtonText, draft.dayOfWeek === index && s.dayActiveText]}>{day.slice(0, 3)}</Text></Pressable>)}</View><View style={s.times}><View style={s.timeField}><Field label="Starts" value={draft.startTime} onChangeText={(v) => setDraft((d) => ({ ...d, startTime: v }))} placeholder="16:00" /></View><View style={s.timeField}><Field label="Ends" value={draft.endTime} onChangeText={(v) => setDraft((d) => ({ ...d, endTime: v }))} placeholder="18:00" /></View></View><Button label="Add window" icon={Plus} variant="secondary" onPress={() => setSlots((current) => [...current, draft])} /></Card><Button label="Publish availability" onPress={save} loading={saving} /></Screen>;
}
const s = StyleSheet.create({ back: { height: 44, justifyContent: 'center' }, title: { color: colors.ink, fontFamily: typography.bold, fontSize: 31 }, copy: { color: colors.muted, fontFamily: typography.regular, fontSize: 15, lineHeight: 22 }, notice: { color: colors.brandStrong, fontFamily: typography.medium }, slot: { flexDirection: 'row', alignItems: 'center' }, clock: { width: 40, height: 40, borderRadius: 8, backgroundColor: colors.brandSoft, alignItems: 'center', justifyContent: 'center' }, slotCopy: { flex: 1 }, day: { color: colors.ink, fontFamily: typography.bold }, time: { color: colors.muted, fontFamily: typography.regular, marginTop: 3 }, delete: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' }, section: { color: colors.ink, fontFamily: typography.bold, fontSize: 17 }, label: { color: colors.ink, fontFamily: typography.medium, fontSize: 13 }, days: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, dayButton: { minWidth: 42, paddingVertical: 9, paddingHorizontal: 8, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 7, alignItems: 'center' }, dayActive: { backgroundColor: colors.brand, borderColor: colors.brand }, dayButtonText: { color: colors.muted, fontFamily: typography.medium, fontSize: 12 }, dayActiveText: { color: colors.white }, times: { flexDirection: 'row', gap: spacing.sm }, timeField: { flex: 1 } });
