import { router } from 'expo-router';
import { ArrowLeft, CalendarPlus } from 'lucide-react-native';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Card, ErrorNotice, Field, LoadingState, Screen } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { request } from '@/lib/api';
import { useData } from '@/lib/hooks';
import { colors, spacing, typography } from '@/theme';

export default function NewSessionScreen() {
  const { user } = useAuth(); const connections = useData<any[]>(() => request('/connections/my-connections'), []); const [selected, setSelected] = useState<number | null>(null); const [form, setForm] = useState({ title: '', subject: '', scheduledDate: '', startTime: '', endTime: '', description: '', meetingLink: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  if (connections.loading) return <LoadingState />; const accepted = (connections.data || []).filter((item) => item.status === 'accepted'); const set = (key: keyof typeof form, value: string) => setForm((f) => ({ ...f, [key]: value }));
  const create = async () => { setSaving(true); setError(''); try { await request('/sessions', { method: 'POST', body: JSON.stringify({ ...form, connectionId: selected }) }); router.replace('/(app)/(tabs)/schedule'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to schedule session'); } finally { setSaving(false); } };
  return <Screen><Pressable onPress={() => router.back()} style={s.back}><ArrowLeft size={22} color={colors.ink} /></Pressable><View style={s.icon}><CalendarPlus size={27} color={colors.brand} /></View><Text style={s.title}>Plan a session</Text><Text style={s.copy}>Choose a connected person and a time inside the tutor’s published availability.</Text>{error || connections.error ? <ErrorNotice message={error || connections.error} /> : null}<Text style={s.label}>Connected person</Text><View style={s.connections}>{accepted.map((item) => { const name = item.tutor_name || item.student_name || 'Connection'; return <Pressable key={item.id} onPress={() => setSelected(item.id)} style={[s.connection, selected === item.id && s.selected]}><Text style={[s.connectionName, selected === item.id && s.selectedText]}>{name}</Text></Pressable>; })}</View>{!accepted.length ? <Card tone="gold"><Text style={s.cardTitle}>No accepted connections yet</Text><Text style={s.copy}>Connect with a tutor or accept a student request before planning a session.</Text></Card> : null}<Field label="Session title" value={form.title} onChangeText={(v) => set('title', v)} placeholder="Algebra practice" /><Field label="Subject" value={form.subject} onChangeText={(v) => set('subject', v)} /><Field label="Date (YYYY-MM-DD)" value={form.scheduledDate} onChangeText={(v) => set('scheduledDate', v)} placeholder="2026-09-25" /><View style={s.times}><View style={s.flex}><Field label="Start (HH:MM)" value={form.startTime} onChangeText={(v) => set('startTime', v)} placeholder="16:00" /></View><View style={s.flex}><Field label="End (HH:MM)" value={form.endTime} onChangeText={(v) => set('endTime', v)} placeholder="17:00" /></View></View><Field label="What will you work on?" value={form.description} onChangeText={(v) => set('description', v)} multiline />{user?.role === 'tutor' ? <><Field label="Custom meeting link (optional)" value={form.meetingLink} onChangeText={(v) => set('meetingLink', v)} placeholder="Leave blank for a managed Zoom room" autoCapitalize="none" /><Text style={s.copy}>A secure Zoom room is prepared automatically after confirmation when the integration is connected.</Text></> : null}<Button label="Request session" onPress={create} loading={saving} disabled={!selected || !form.title || !form.scheduledDate || !form.startTime || !form.endTime} /></Screen>;
}
const s = StyleSheet.create({ back: { height: 44, justifyContent: 'center' }, icon: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.brandSoft, alignItems: 'center', justifyContent: 'center' }, title: { color: colors.ink, fontFamily: typography.bold, fontSize: 31 }, copy: { color: colors.muted, fontFamily: typography.regular, fontSize: 14, lineHeight: 21 }, label: { color: colors.ink, fontFamily: typography.bold, fontSize: 14 }, connections: { gap: spacing.sm }, connection: { borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, borderRadius: 8, padding: spacing.lg }, selected: { borderColor: colors.brand, backgroundColor: colors.brandSoft }, connectionName: { color: colors.ink, fontFamily: typography.medium }, selectedText: { color: colors.brandStrong, fontFamily: typography.bold }, times: { flexDirection: 'row', gap: spacing.sm }, flex: { flex: 1 }, cardTitle: { color: colors.gold, fontFamily: typography.bold } });
