import { router } from 'expo-router';
import { ArrowLeft, CheckCircle2, Circle, Plus, Target, Trash2 } from 'lucide-react-native';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Card, EmptyState, ErrorNotice, Field, LoadingState, Screen } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { request } from '@/lib/api';
import { useData } from '@/lib/hooks';
import { colors, spacing, typography } from '@/theme';

export default function ProgressScreen() {
  const { user } = useAuth(); const [form, setForm] = useState({ subject: '', title: '', description: '' }); const [showForm, setShowForm] = useState(false); const [error, setError] = useState('');
  const state = useData<any>(async () => { if (user?.role === 'student') return request('/progress/goals'); const connections = await request<any[]>('/connections/my-connections'); if (!connections.length) return { goals: [], student: null }; return request(`/progress/goals?studentId=${connections[0].student_id}`); }, [user?.role]);
  if (state.loading) return <LoadingState />; const goals = state.data?.goals || [];
  const create = async () => { setError(''); try { await request('/progress/goals', { method: 'POST', body: JSON.stringify(form) }); setForm({ subject: '', title: '', description: '' }); setShowForm(false); state.reload(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create goal'); } };
  const toggleMilestone = async (id: number, done: boolean) => { await request(`/progress/milestones/${id}`, { method: 'PATCH', body: JSON.stringify({ isCompleted: !done }) }); state.reload(); };
  const addMilestone = async (goalId: number) => { await request(`/progress/goals/${goalId}/milestones`, { method: 'POST', body: JSON.stringify({ title: 'New milestone' }) }); state.reload(); };
  const remove = async (goalId: number) => { await request(`/progress/goals/${goalId}`, { method: 'DELETE' }); state.reload(); };
  return <Screen refreshing={state.refreshing} onRefresh={state.reload}><Pressable onPress={() => router.back()} style={s.back}><ArrowLeft size={22} color={colors.ink} /></Pressable><View style={s.header}><View style={s.headerCopy}><Text style={s.title}>{user?.role === 'student' ? 'Learning goals' : 'Student progress'}</Text><Text style={s.copy}>{user?.role === 'student' ? 'Break a big outcome into steps you can see and celebrate.' : `Review goals shared by ${state.data?.student?.name || 'your connected student'}.`}</Text></View>{user?.role === 'student' ? <Pressable style={s.add} onPress={() => setShowForm(!showForm)}><Plus size={21} color={colors.white} /></Pressable> : null}</View>{error || state.error ? <ErrorNotice message={error || state.error} /> : null}{showForm ? <Card tone="brand"><Text style={s.section}>Create a goal</Text><Field label="Subject" value={form.subject} onChangeText={(v) => setForm((f) => ({ ...f, subject: v }))} /><Field label="Goal" value={form.title} onChangeText={(v) => setForm((f) => ({ ...f, title: v }))} /><Field label="What does success look like?" value={form.description} onChangeText={(v) => setForm((f) => ({ ...f, description: v }))} multiline /><Button label="Create goal" onPress={create} disabled={!form.subject || !form.title} /></Card> : null}{goals.length ? goals.map((goal: any) => <Card key={goal.id}><View style={s.goalTop}><View style={s.goalCopy}><Text style={s.subject}>{goal.subject}</Text><Text style={s.goalTitle}>{goal.title}</Text></View><Text style={s.percent}>{goal.progress_percent}%</Text></View><View style={s.bar}><View style={[s.barFill, { width: `${goal.progress_percent}%` }]} /></View>{goal.description ? <Text style={s.description}>{goal.description}</Text> : null}<View style={s.milestones}>{(goal.milestones || []).map((item: any) => <Pressable key={item.id} onPress={() => user?.role === 'student' && toggleMilestone(item.id, item.is_completed)} style={s.milestone}>{item.is_completed ? <CheckCircle2 size={20} color={colors.green} /> : <Circle size={20} color={colors.muted} />}<Text style={[s.milestoneText, item.is_completed && s.completed]}>{item.title}</Text></Pressable>)}</View>{user?.role === 'student' ? <View style={s.goalActions}><Button label="Add milestone" icon={Plus} variant="secondary" onPress={() => addMilestone(goal.id)} style={s.flex} /><Pressable onPress={() => remove(goal.id)} style={s.trash}><Trash2 size={20} color={colors.red} /></Pressable></View> : null}</Card>) : <EmptyState icon={Target} title="No learning goals yet" message={user?.role === 'student' ? 'Create a goal and divide it into small, visible milestones.' : 'This student has not shared a goal yet.'} />}</Screen>;
}
const s = StyleSheet.create({ back: { height: 44, justifyContent: 'center' }, header: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, headerCopy: { flex: 1, gap: 5 }, title: { color: colors.ink, fontFamily: typography.bold, fontSize: 31 }, copy: { color: colors.muted, fontFamily: typography.regular, fontSize: 14, lineHeight: 21 }, add: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center' }, section: { color: colors.ink, fontFamily: typography.bold, fontSize: 17 }, goalTop: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, goalCopy: { flex: 1, gap: 3 }, subject: { color: colors.brand, fontFamily: typography.bold, fontSize: 11, textTransform: 'uppercase' }, goalTitle: { color: colors.ink, fontFamily: typography.bold, fontSize: 18 }, percent: { color: colors.brandStrong, fontFamily: typography.bold, fontSize: 18 }, bar: { height: 7, borderRadius: 4, backgroundColor: '#E6E1D9', overflow: 'hidden' }, barFill: { height: 7, backgroundColor: colors.brand }, description: { color: colors.muted, lineHeight: 20 }, milestones: { gap: spacing.sm }, milestone: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, milestoneText: { flex: 1, color: colors.ink, fontFamily: typography.regular }, completed: { color: colors.muted, textDecorationLine: 'line-through' }, goalActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, flex: { flex: 1 }, trash: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center' } });
