import Constants from 'expo-constants';
import * as Device from 'expo-device';
import * as Notifications from 'expo-notifications';
import { router } from 'expo-router';
import { ArrowLeft, BellRing, KeyRound, Trash2 } from 'lucide-react-native';
import { useState } from 'react';
import { Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Card, ErrorNotice, Field, Header, Screen } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { api, request } from '@/lib/api';
import { colors, spacing, typography } from '@/theme';

export default function SettingsScreen() {
  const { clearSession } = useAuth(); const [passwords, setPasswords] = useState({ current: '', next: '' }); const [deletePassword, setDeletePassword] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [working, setWorking] = useState('');
  const changePassword = async () => { setWorking('password'); setError(''); try { await request('/users/change-password', { method: 'PUT', body: JSON.stringify({ currentPassword: passwords.current, newPassword: passwords.next }) }); setNotice('Password updated.'); setPasswords({ current: '', next: '' }); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to change password'); } finally { setWorking(''); } };
  const enablePush = async () => { setWorking('push'); setError(''); try { if (!Device.isDevice) throw new Error('Push notifications require a physical device.'); const permission = await Notifications.requestPermissionsAsync(); if (!permission.granted) throw new Error('Notification permission was not granted.'); const projectId = Constants.easConfig?.projectId || Constants.expoConfig?.extra?.eas?.projectId; if (!projectId) throw new Error('Push notifications will activate after the first EAS project build.'); const token = (await Notifications.getExpoPushTokenAsync({ projectId })).data; await api.registerPushToken({ token, platform: Platform.OS, deviceName: Constants.deviceName || 'Mobile device' }); setNotice('Push notifications are enabled on this device.'); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to enable notifications'); } finally { setWorking(''); } };
  const deleteAccount = async () => { setWorking('delete'); setError(''); try { await api.deleteAccount(deletePassword); await clearSession(); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete account'); } finally { setWorking(''); } };
  return <Screen><Pressable onPress={() => router.back()} style={s.back}><ArrowLeft size={22} color={colors.ink} /></Pressable><Header eyebrow="Privacy and access" title="Account settings" subtitle="Manage security, device notifications, and your account data." />{error ? <ErrorNotice message={error} /> : null}{notice ? <Card tone="brand"><Text style={s.notice}>{notice}</Text></Card> : null}<Card><View style={s.sectionHead}><KeyRound size={21} color={colors.brand} /><Text style={s.section}>Change password</Text></View><Field label="Current password" value={passwords.current} onChangeText={(v) => setPasswords((p) => ({ ...p, current: v }))} secureTextEntry /><Field label="New password" value={passwords.next} onChangeText={(v) => setPasswords((p) => ({ ...p, next: v }))} secureTextEntry /><Button label="Update password" variant="secondary" onPress={changePassword} loading={working === 'password'} disabled={!passwords.current || passwords.next.length < 8} /></Card><Card><View style={s.sectionHead}><BellRing size={21} color={colors.brand} /><Text style={s.section}>Device notifications</Text></View><Text style={s.copy}>Receive message, session, request, and reminder notifications on this phone.</Text><Button label="Enable notifications" variant="secondary" onPress={enablePush} loading={working === 'push'} /></Card><Card tone="coral"><View style={s.sectionHead}><Trash2 size={21} color={colors.red} /><Text style={[s.section, s.danger]}>Delete account</Text></View><Text style={s.copy}>This permanently removes your profile, conversations, connections, sessions, and account data. It cannot be undone.</Text><Field label="Current password to confirm" value={deletePassword} onChangeText={setDeletePassword} secureTextEntry /><Button label="Permanently delete my account" variant="danger" onPress={deleteAccount} loading={working === 'delete'} disabled={!deletePassword} /></Card></Screen>;
}
const s = StyleSheet.create({ back: { height: 44, justifyContent: 'center' }, notice: { color: colors.brandStrong, fontFamily: typography.medium }, sectionHead: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, section: { color: colors.ink, fontFamily: typography.bold, fontSize: 17 }, danger: { color: colors.red }, copy: { color: colors.muted, fontFamily: typography.regular, lineHeight: 21 } });
