import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, Ban, Bookmark, Flag, GraduationCap, HeartHandshake, MapPin, Star } from 'lucide-react-native';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Avatar, Button, Card, Chip, ErrorNotice, LoadingState, Screen, SectionTitle } from '@/components/ui';
import { request } from '@/lib/api';
import { useData } from '@/lib/hooks';
import { colors, spacing, typography } from '@/theme';
import type { Tutor } from '@/types';

export default function TutorDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const state = useData<Tutor>(() => request(`/users/tutors/${id}`), [id]); const [notice, setNotice] = useState(''); const [working, setWorking] = useState(false);
  const connect = async () => { setWorking(true); try { const result = await request<{ message: string }>('/connections/request', { method: 'POST', body: JSON.stringify({ tutorId: Number(id) }) }); setNotice(result.message); } catch (e) { setNotice(e instanceof Error ? e.message : 'Unable to send request'); } finally { setWorking(false); } };
  const favorite = async () => { try { await request(`/favorites/${id}`, { method: 'POST' }); setNotice('Tutor saved to your shortlist.'); } catch (e) { setNotice(e instanceof Error ? e.message : 'Unable to save tutor'); } };
  const report = () => Alert.alert('Report this tutor?', 'A private safety report will be sent to the NextDoorLearn moderation team for review.', [
    { text: 'Cancel', style: 'cancel' },
    { text: 'Submit report', onPress: async () => { try { await request('/reports', { method: 'POST', body: JSON.stringify({ reportedUserId: Number(id), reason: 'Safety concern', details: 'Submitted from the mobile tutor profile.' }) }); setNotice('Report submitted. The moderation team will review it.'); } catch (e) { setNotice(e instanceof Error ? e.message : 'Unable to submit report'); } } },
  ]);
  const block = () => Alert.alert('Block this tutor?', 'You will no longer be able to find, message, or schedule with each other.', [
    { text: 'Cancel', style: 'cancel' },
    { text: 'Block tutor', style: 'destructive', onPress: async () => { try { await request(`/blocks/${id}`, { method: 'POST', body: JSON.stringify({ reason: 'Blocked from tutor profile' }) }); router.replace('/tutors'); } catch (e) { setNotice(e instanceof Error ? e.message : 'Unable to block tutor'); } } },
  ]);
  if (state.loading) return <LoadingState />; if (!state.data) return <Screen><ErrorNotice message={state.error || 'Tutor not found'} /></Screen>; const tutor = state.data;
  return <Screen><Pressable onPress={() => router.back()} style={styles.back}><ArrowLeft size={22} color={colors.ink} /></Pressable><View style={styles.hero}><Avatar name={tutor.name} uri={tutor.avatar_url} size={92} /><View style={styles.heroCopy}><Text style={styles.name}>{tutor.name}</Text><Text style={styles.headline}>{tutor.headline || 'Community tutor'}</Text><View style={styles.inline}><Star size={15} fill={colors.gold} color={colors.gold} /><Text style={styles.rating}>{Number(tutor.averageRating || 0).toFixed(1)} ({tutor.totalReviews || 0})</Text></View></View></View><View style={styles.chips}>{(tutor.subjects || []).map((subject) => <Chip key={subject} label={subject} />)}<Chip label={Number(tutor.hourly_rate || 0) === 0 ? 'Volunteer' : `$${tutor.hourly_rate}/hr`} tone="gold" /></View>{notice ? <Card tone="brand"><Text style={styles.notice}>{notice}</Text></Card> : null}<View style={styles.actions}><Button label="Request to connect" icon={HeartHandshake} onPress={connect} loading={working} style={styles.mainAction} /><Button label="Save" icon={Bookmark} variant="secondary" onPress={favorite} /></View><Card><SectionTitle>About</SectionTitle><Text style={styles.body}>{tutor.bio || tutor.motivation || 'This tutor is ready to help students build confidence and skill.'}</Text></Card><Card><View style={styles.detail}><GraduationCap size={20} color={colors.brand} /><View style={styles.detailCopy}><Text style={styles.detailTitle}>Experience and approach</Text><Text style={styles.body}>{tutor.education || 'Education details coming soon.'}{tutor.experience_years ? ` · ${tutor.experience_years} years of experience` : ''}</Text><Text style={styles.body}>{tutor.teaching_style || 'Teaching style details coming soon.'}</Text></View></View>{tutor.location ? <View style={styles.detail}><MapPin size={20} color={colors.coral} /><View style={styles.detailCopy}><Text style={styles.detailTitle}>Location and format</Text><Text style={styles.body}>{tutor.location} · {tutor.tutoring_mode || 'Flexible'}</Text></View></View> : null}</Card><Card tone="coral"><SectionTitle>Safety tools</SectionTitle><Text style={styles.body}>Reports are private. Blocking removes this person from your matches and communication.</Text><View style={styles.actions}><Button label="Report" icon={Flag} variant="secondary" onPress={report} style={styles.mainAction} /><Button label="Block" icon={Ban} variant="danger" onPress={block} style={styles.mainAction} /></View></Card></Screen>;
}
const styles = StyleSheet.create({ back: { width: 44, height: 44, justifyContent: 'center' }, hero: { flexDirection: 'row', alignItems: 'center', gap: spacing.lg }, heroCopy: { flex: 1, gap: 4 }, name: { color: colors.ink, fontFamily: typography.bold, fontSize: 28 }, headline: { color: colors.muted, fontFamily: typography.regular, lineHeight: 20 }, inline: { flexDirection: 'row', alignItems: 'center', gap: 5 }, rating: { color: colors.gold, fontFamily: typography.bold, fontSize: 13 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, actions: { flexDirection: 'row', gap: spacing.sm, flexWrap: 'wrap' }, mainAction: { flex: 1 }, notice: { color: colors.brandStrong, fontFamily: typography.medium }, body: { color: colors.muted, fontFamily: typography.regular, fontSize: 14, lineHeight: 21 }, detail: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md }, detailCopy: { flex: 1, gap: 5 }, detailTitle: { color: colors.ink, fontFamily: typography.bold, fontSize: 15 } });
