import { router } from 'expo-router';
import { Bell, BookOpenCheck, CalendarClock, CircleHelp, ClipboardList, HeartHandshake, LogOut, Settings, ShieldCheck, Target, UserRound } from 'lucide-react-native';
import { StyleSheet, Text, View } from 'react-native';
import { FeatureRow } from '@/components/FeatureRow';
import { Avatar, Card, Header, Screen } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { colors, spacing, typography } from '@/theme';

export default function MoreScreen() {
  const { user, signOut } = useAuth(); const tutor = user?.role === 'tutor';
  return <Screen><Header eyebrow="Account and tools" title="More" /><Card style={styles.profile}><Avatar name={user?.name || 'User'} size={56} /><View style={styles.profileCopy}><Text style={styles.name}>{user?.name}</Text><Text style={styles.role}>{tutor ? 'Tutor' : 'Student'} · {user?.email}</Text></View></Card><View style={styles.group}><FeatureRow icon={UserRound} title="Profile" subtitle="Photo, bio, contact details, and preferences" onPress={() => router.push('/(app)/profile')} />{tutor ? <FeatureRow icon={CalendarClock} title="Availability" subtitle="Set recurring hours students can request" onPress={() => router.push('/(app)/availability')} /> : <><FeatureRow icon={ClipboardList} title="Learning-needs intake" subtitle="Subjects, learning style, schedule, and budget" onPress={() => router.push('/(app)/intake')} /><FeatureRow icon={Target} title="Learning goals" subtitle="Goals, milestones, and progress" onPress={() => router.push('/(app)/progress')} /></>}<FeatureRow icon={BookOpenCheck} title={tutor ? 'Student progress' : 'Session history'} subtitle={tutor ? 'Review goals shared by your students' : 'Completed sessions and reflections'} onPress={() => router.push(tutor ? '/(app)/progress' : '/(app)/(tabs)/schedule')} /></View><View style={styles.group}><FeatureRow icon={Bell} title="Notifications" subtitle="Requests, messages, reminders, and updates" onPress={() => router.push('/(app)/notifications')} /><FeatureRow icon={HeartHandshake} title="Sponsor student access" subtitle="Start a sponsorship conversation" onPress={() => router.push('/(auth)/donate')} /><FeatureRow icon={ShieldCheck} title="Safety center" subtitle="Blocked accounts and reporting support" onPress={() => router.push('/(app)/safety')} />{user?.isAdmin ? <FeatureRow icon={Settings} title="Administration" subtitle="Users, applications, reports, and waitlist" onPress={() => router.push('/(app)/admin')} /> : null}<FeatureRow icon={CircleHelp} title="Help and policies" subtitle="Support, privacy, and community standards" onPress={() => router.push('/(app)/help')} /></View><View style={styles.group}><FeatureRow icon={Settings} title="Account settings" subtitle="Password, notifications, and account deletion" onPress={() => router.push('/(app)/settings')} /><FeatureRow icon={LogOut} title="Log out" onPress={signOut} danger /></View></Screen>;
}
const styles = StyleSheet.create({ profile: { flexDirection: 'row', alignItems: 'center' }, profileCopy: { flex: 1, gap: 3 }, name: { color: colors.ink, fontFamily: typography.bold, fontSize: 17 }, role: { color: colors.muted, fontFamily: typography.regular, fontSize: 12 }, group: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 8, paddingHorizontal: spacing.md } });
