import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, Send } from 'lucide-react-native';
import { useEffect, useRef, useState } from 'react';
import { FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Avatar, ErrorNotice, LoadingState } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { request } from '@/lib/api';
import { useData } from '@/lib/hooks';
import { colors, spacing, typography } from '@/theme';

type Message = { id: number; sender_id: number; sender_name: string; content: string; timestamp: string };
export default function ConversationScreen() {
  const params = useLocalSearchParams<{ id: string; name?: string }>(); const { user } = useAuth(); const [message, setMessage] = useState(''); const [sending, setSending] = useState(false); const list = useRef<FlatList<Message>>(null);
  const state = useData<Message[]>(() => request(`/messages/${params.id}`), [params.id]);
  useEffect(() => { if (state.data?.length) setTimeout(() => list.current?.scrollToEnd({ animated: false }), 50); }, [state.data]);
  const send = async () => { const content = message.trim(); if (!content) return; setSending(true); setMessage(''); try { await request('/messages/send', { method: 'POST', body: JSON.stringify({ connectionId: Number(params.id), content }) }); state.reload(); } catch { setMessage(content); } finally { setSending(false); } };
  if (state.loading) return <LoadingState />;
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><ArrowLeft size={22} color={colors.ink} /></Pressable><Avatar name={params.name || 'Conversation'} size={38} /><View style={styles.heading}><Text style={styles.name}>{params.name || 'Conversation'}</Text><Text style={styles.status}>NextDoorLearn connection</Text></View></View>{state.error ? <ErrorNotice message={state.error} /> : null}<FlatList ref={list} data={state.data || []} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.messages} renderItem={({ item }) => { const mine = Number(item.sender_id) === Number(user?.id); return <View style={[styles.bubble, mine ? styles.mine : styles.theirs]}><Text style={[styles.body, mine && styles.mineBody]}>{item.content}</Text><Text style={[styles.time, mine && styles.mineTime]}>{formatTime(item.timestamp)}</Text></View>; }} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>Start the conversation</Text><Text style={styles.emptyCopy}>A simple introduction is a good place to begin.</Text></View>} /><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.composer}><TextInput value={message} onChangeText={setMessage} placeholder="Write a message" placeholderTextColor="#8A948F" multiline style={styles.input} /><Pressable disabled={!message.trim() || sending} onPress={send} style={[styles.send, (!message.trim() || sending) && styles.disabled]}><Send size={20} color={colors.white} /></Pressable></View></KeyboardAvoidingView></SafeAreaView>;
}
const formatTime = (value: string) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' }); };
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, header: { height: 68, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.line, backgroundColor: colors.surface }, back: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' }, heading: { flex: 1 }, name: { color: colors.ink, fontFamily: typography.bold, fontSize: 15 }, status: { color: colors.muted, fontFamily: typography.regular, fontSize: 11 }, messages: { padding: spacing.lg, gap: spacing.sm, flexGrow: 1 }, bubble: { maxWidth: '82%', borderRadius: 16, paddingHorizontal: spacing.md, paddingVertical: 10, gap: 4 }, mine: { alignSelf: 'flex-end', backgroundColor: colors.brand, borderBottomRightRadius: 4 }, theirs: { alignSelf: 'flex-start', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderBottomLeftRadius: 4 }, body: { color: colors.ink, fontFamily: typography.regular, fontSize: 15, lineHeight: 21 }, mineBody: { color: colors.white }, time: { color: colors.muted, fontSize: 9 }, mineTime: { color: '#C9E8E3', textAlign: 'right' }, composer: { flexDirection: 'row', alignItems: 'flex-end', gap: spacing.sm, padding: spacing.md, borderTopWidth: 1, borderTopColor: colors.line, backgroundColor: colors.surface }, input: { flex: 1, minHeight: 44, maxHeight: 110, borderWidth: 1, borderColor: colors.line, borderRadius: 22, paddingHorizontal: spacing.lg, paddingTop: 11, color: colors.ink, backgroundColor: colors.background, fontSize: 15 }, send: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center' }, disabled: { opacity: 0.4 }, empty: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: spacing.sm }, emptyTitle: { color: colors.ink, fontFamily: typography.bold, fontSize: 18 }, emptyCopy: { color: colors.muted } });
